### ISSUE TITLE
Provide auth-db config details at runtime

### ISSUE THREAD

**Issue by dazza-codes** [sul-dlss/ld4p-marc21-to-xml#22]
At present, the auth-db connection is configured by providing a custom property file in `java/src/main/resources/server.conf` for the build system to incorporate into the packaged JAR.  When this file is not provided for the build, there is no way to configure the auth-db connection.  To enhance the code, it would be great to provide it at runtime. This could be enabled by adding a command line option to the MarcToXML class, so it could be called with an option to read from any config file at runtime.

**Comment by dazza-codes** [comment]
Brief discussion with @eefahy concluded with:
- provide command line options for the db-connection
  - one option could be a path to a runtime properties file  OR
  - other options could specify each of the connection properties
- use ENV values if there are no command line values given
- use defaults from a properties file if there are no ENV values given

**Comment by ndushay** [comment]
related to #29

**Comment by dazza-codes** [comment]
Related to https://github.com/sul-dlss/ld4p-marc21-to-xml/issues/27
