### ISSUE TITLE
Should MarcToXML accept an input stream of marc21?

### ISSUE THREAD

**Issue by jgreben** [sul-dlss/ld4p-marc21-to-xml#25]
Currently the `-i` option allows for the conversion of a file of marc21. For services like "ckey2bibframe" that call the MarcToXML class via the JAR file, can we extend the class to accept an input stream of marc21 data instead of just a file? This would save the ckey2bibframe app the work of having to create a file and then discard it every time.

**Comment by dazza-codes** [comment]
Basically, if no file is specified, it could assume the STDIN stream contains the data?

**Comment by dazza-codes** [comment]
We might want a new class for this use case, one that only reads from STDIN and outputs to STDOUT, without any logging etc.  Maybe call it `MarcToXMLStreams`?

**Comment by dazza-codes** [comment]
Need to check how marc4j handles STDIN streams and whether it needs an intermediate java IO stream object or creates one automatically.

**Comment by jgreben** [comment]
If that were the case, the rails app call would look something like this(?):
```
def marc21_to_xml(catalogdump)
    jar = 'lib/xform-marc21-to-xml-jar-with-dependencies.jar'
    system("java -cp #{jar} edu.stanford.MarcToXMLStreams #{catalogdump} > /tmp/#{ckey}.xml")
  end
```

**Comment by dazza-codes** [comment]
BTW, consider using a ruby temporary file instead of a hardcoded `/tmp` path (which does not work on a system without that path), e.g. https://www.safaribooksonline.com/library/view/ruby-cookbook/0596523696/ch06s08.html
