### ISSUE TITLE
create deployable artifact on travis

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/ld4p-marc21-to-xml#29]
then versioned url could be used to deploy code to webforms AND converter VMs.

**Comment by ndushay** [comment]
original idea:  do explicit github versioned releases on this repo;  change travis to run AND create a deployable artifact;  then use travis artifact when deploying to both converter VM and libsys-webforms VM.

currently, code expects an external config file.

on libsys-webforms VM, for now: the jar that has a config built into it was created on Josh's laptop and copied to correct spot for webforms to work.

Todo:

1.  cut a version 
2.  update travis to ship jar back to github release
3. puppet changes to libsys-webforms to use github release jar

only works for now on libsys-webform-dev box.

4.  use same mechanism with puppet for converter VM.

**Comment by ndushay** [comment]
Darren has questions for Erin before he can proceed with this

**Comment by dazza-codes** [comment]
The ld4p-marc21-to-xml repo now contains java code that does not require a private config file to be built into the packaged JAR.

**Comment by dazza-codes** [comment]
I’m wondering whether this entails that every time travis builds it could create a new release artifact, esp. when we don’t intend for a PR to create a new release artifact.  I’m a bit confused by the workflow to separate "development-travis-build" from a "release-travis-build".  AFAIK, I don't think we want travis to release an artifact every time it has a successful build.

**Comment by jgreben** [comment]
I personally don't see building a jar file as an artifact for every build as being a problem at this point, especially since there is not much if any churn on this repo. There is however a lot of churn on the libsys-webforms repo, and currently we have to manually copy over the jar file every time we deploy. So from my perspective, having a release build for every PR is an acceptable trade-off.

**Comment by jgreben** [comment]
Closed by https://github.com/sul-dlss/ld4p-marc21-to-xml/pull/41
